# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#Box settings
  config.vm.box = "kalilinux/rolling"
  
# Example for VirtualBox:
#
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = "4"

  # config.vm.network "private_network", ip: "10.1.1.1"
    
  end



  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
  curl -sSL https://websploit.org/install.sh | sudo bash 

  SHELL
end
